schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_68-baseline"
description = ""
authors = []
keywords = []
[metadata]
task_id = "baseline"
task_type = "swe"
mode = "baseline"
repo_name = "ansible/ansible"
task_attempt_id = "69839e79db8f5e922c44f807__69c42201029d24509a863611"
image_name = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:d6fbea3a7c537cd4e055c97ddf5c2d3454b72cf512ab6c29a3f4be2e27ae538d"
tags = [ "swe", "baseline", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:d6fbea3a7c537cd4e055c97ddf5c2d3454b72cf512ab6c29a3f4be2e27ae538d"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
