version = "1.0"

[metadata]
task_id = "baseline"
task_type = "swe"
mode = "baseline"
repo_name = "flipt-io/flipt"
task_attempt_id = "69836ee4987091d7e86e449e__69bdc3cfa4db2357e6d76eee"
image_name = "hilbench-swe:69bdc3cfa4db2357e6d76eee"
tags = ["swe", "baseline", "hil-bench"]

[verifier]
timeout_sec = 1800.0

[agent]
timeout_sec = 7200.0

[environment]
docker_image = "hilbench-swe:69bdc3cfa4db2357e6d76eee"
build_timeout_sec = 1200.0
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
