schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_74-full_info"
description = ""
authors = []
keywords = []
[metadata]
task_id = "full_info"
task_type = "swe"
mode = "full_info"
repo_name = "ansible/ansible"
task_attempt_id = "698648c3283d42a760567539__69c2a3769cf07c8af4c86ed3"
image_name = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:e687f8e329a73432d2abb6c435b11dfdf1cf5ceff2a99c5fcb90b046dac78e3e"
tags = [ "swe", "full_info", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:e687f8e329a73432d2abb6c435b11dfdf1cf5ceff2a99c5fcb90b046dac78e3e"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
