schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_39-full_info"
description = ""
authors = []
keywords = []
[metadata]
task_id = "full_info"
task_type = "swe"
mode = "full_info"
repo_name = "navidrome/navidrome"
task_attempt_id = "69836ee4987091d7e86e44a9__69bc770c46c091045f6a9348"
image_name = "hilbench-swe:69bc770c46c091045f6a9348"
tags = [ "swe", "full_info", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "hilbench-swe:69bc770c46c091045f6a9348"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
