schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_19-baseline"
description = ""
authors = []
keywords = []
[metadata]
task_id = "baseline"
task_type = "swe"
mode = "baseline"
repo_name = "ansible/ansible"
task_attempt_id = "6978fa4d0df9703f1e96f3e1__69b1031f73a8f5979167a774"
image_name = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:a67b7c2fb7cc14f8f00240d6eaee663a68fd0dce823ea8e26d57d2b7a0d9ab4a"
tags = [ "swe", "baseline", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:a67b7c2fb7cc14f8f00240d6eaee663a68fd0dce823ea8e26d57d2b7a0d9ab4a"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
