schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_64-baseline"
description = ""
authors = []
keywords = []
[metadata]
task_id = "baseline"
task_type = "swe"
mode = "baseline"
repo_name = "flipt-io/flipt"
task_attempt_id = "69836ee4987091d7e86e449e__69bdc3cfa4db2357e6d76eee"
image_name = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:cb5870e22155169373034c55b9bfb45df5f467c303b2bf54b37582c6d6a66766"
tags = [ "swe", "baseline", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:cb5870e22155169373034c55b9bfb45df5f467c303b2bf54b37582c6d6a66766"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
