schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_90-full_info"
description = ""
authors = []
keywords = []
[metadata]
task_id = "full_info"
task_type = "swe"
mode = "full_info"
repo_name = "protonmail/webclients"
task_attempt_id = "6978fa4d0df9703f1e96f3f5__69b5d0fd12a35f718e17cef9"
image_name = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:69534d76fcc94608c86dffb8e2a1cd1d9252a4747e727b12309b23457da4cf83"
tags = [ "swe", "full_info", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:69534d76fcc94608c86dffb8e2a1cd1d9252a4747e727b12309b23457da4cf83"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
