schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_31-baseline"
description = ""
authors = []
keywords = []
[metadata]
task_id = "baseline"
task_type = "swe"
mode = "baseline"
repo_name = "protonmail/webclients"
task_attempt_id = "698648c3283d42a760567553__69adb026280564ea75773a58"
image_name = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:5b93f7653e9fee82e7ccfc3c531f2579d6e8a648412dfb8144da52153fe2b278"
tags = [ "swe", "baseline", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:5b93f7653e9fee82e7ccfc3c531f2579d6e8a648412dfb8144da52153fe2b278"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
