schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_77-full_info"
description = ""
authors = []
keywords = []
[metadata]
task_id = "full_info"
task_type = "swe"
mode = "full_info"
repo_name = "ansible/ansible"
task_attempt_id = "6978fa4d0df9703f1e96f3ec__69c236b1f424c8050d11a201"
image_name = "hilbench-swe:69c236b1f424c8050d11a201"
tags = [ "swe", "full_info", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "hilbench-swe:69c236b1f424c8050d11a201"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
