version = "1.0"

[metadata]
task_id = "full_info"
task_type = "swe"
mode = "full_info"
repo_name = "ansible/ansible"
task_attempt_id = "698648c3283d42a76056753b__69c1d02390b4d1152fb37778"
image_name = "hilbench-swe:69c1d02390b4d1152fb37778"
tags = ["swe", "full_info", "hil-bench"]

[verifier]
timeout_sec = 1800.0

[agent]
timeout_sec = 7200.0

[environment]
docker_image = "hilbench-swe:69c1d02390b4d1152fb37778"
build_timeout_sec = 1200.0
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
