schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_91-baseline"
description = ""
authors = []
keywords = []
[metadata]
task_id = "baseline"
task_type = "swe"
mode = "baseline"
repo_name = "ansible/ansible"
task_attempt_id = "698648c3283d42a76056753d__69be182c71bcad4f1c10acba"
image_name = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:6cd8e32608b234553efe4481f23d1c39327e30676c4ea37bb5c67dc548ff2dcc"
tags = [ "swe", "baseline", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:6cd8e32608b234553efe4481f23d1c39327e30676c4ea37bb5c67dc548ff2dcc"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
