version = "1.0"

[metadata]
task_id = "baseline"
task_type = "swe"
mode = "baseline"
repo_name = "navidrome/navidrome"
task_attempt_id = "698648c3283d42a760567547__69af9047352d3e1ddd448e1f"
image_name = "hilbench-swe:69af9047352d3e1ddd448e1f"
tags = ["swe", "baseline", "hil-bench"]

[verifier]
timeout_sec = 1800.0

[agent]
timeout_sec = 7200.0

[environment]
docker_image = "hilbench-swe:69af9047352d3e1ddd448e1f"
build_timeout_sec = 1200.0
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
