schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_38-full_info"
description = ""
authors = []
keywords = []
[metadata]
task_id = "full_info"
task_type = "swe"
mode = "full_info"
repo_name = "navidrome/navidrome"
task_attempt_id = "698648c3283d42a760567548__69b30d9456d2a0ea971aa5f8"
image_name = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:407bc8ea8fca10ed77d394e400a86c8cc697e0e30366c89374d462439d3c67c0"
tags = [ "swe", "full_info", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:407bc8ea8fca10ed77d394e400a86c8cc697e0e30366c89374d462439d3c67c0"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
