schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_0-full_info"
description = ""
authors = []
keywords = []
[metadata]
task_id = "full_info"
task_type = "swe"
mode = "full_info"
repo_name = "ansible/ansible"
task_attempt_id = "6978fa4d0df9703f1e96f3f1__698139c7dc5e90df07566a6c"
image_name = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:8e68dfc4d5f981cfc9d8d1d01306259c35e3f240840f8d9445eaabab2309fd53"
tags = [ "swe", "full_info", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:8e68dfc4d5f981cfc9d8d1d01306259c35e3f240840f8d9445eaabab2309fd53"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
