schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_34-baseline"
description = ""
authors = []
keywords = []
[metadata]
task_id = "baseline"
task_type = "swe"
mode = "baseline"
repo_name = "ansible/ansible"
task_attempt_id = "69836ee4987091d7e86e44dd__69c4be15ecee678a8ac3f143"
image_name = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:708b0f747482e840e5c98075aba10dc9591a97b4af330a0a13a3f6e1f9f438f3"
tags = [ "swe", "baseline", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:708b0f747482e840e5c98075aba10dc9591a97b4af330a0a13a3f6e1f9f438f3"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
