schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_10-baseline"
description = ""
authors = []
keywords = []
[metadata]
task_id = "baseline"
task_type = "swe"
mode = "baseline"
repo_name = "ansible/ansible"
task_attempt_id = "69b37d1c972ca8745b4e8f67__69c3f3301734592b5a14a3b9"
image_name = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:0876d92917c0aa8cd7c26b56bd5cf4b8af6158c839bb6f8b46c5e13d8a358296"
tags = [ "swe", "baseline", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:0876d92917c0aa8cd7c26b56bd5cf4b8af6158c839bb6f8b46c5e13d8a358296"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
