version = "1.0"

[metadata]
task_id = "baseline"
task_type = "swe"
mode = "baseline"
repo_name = "protonmail/webclients"
task_attempt_id = "6978fa4d0df9703f1e96f3eb__69af8d95daf683f67c16245b"
image_name = "hilbench-swe:69af8d95daf683f67c16245b"
tags = ["swe", "baseline", "hil-bench"]

[verifier]
timeout_sec = 1800.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1200.0
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
