schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_18-baseline"
description = ""
authors = []
keywords = []
[metadata]
task_id = "baseline"
task_type = "swe"
mode = "baseline"
repo_name = "flipt-io/flipt"
task_attempt_id = "69836ee4987091d7e86e449d__69c196fa0b42d9b078f32b2e"
image_name = "hilbench-swe:69c196fa0b42d9b078f32b2e"
tags = [ "swe", "baseline", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "hilbench-swe:69c196fa0b42d9b078f32b2e"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
