schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_48-full_info"
description = ""
authors = []
keywords = []
[metadata]
task_id = "full_info"
task_type = "swe"
mode = "full_info"
repo_name = "ansible/ansible"
task_attempt_id = "697a24959fe5d827d73acb13__69b84347019d094e27c4ff42"
image_name = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:e45bc5056e1b7f1b7c2e2722939fc310df247ecc6b3e5c04d957875a8c856d8e"
tags = [ "swe", "full_info", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:e45bc5056e1b7f1b7c2e2722939fc310df247ecc6b3e5c04d957875a8c856d8e"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
