version = "1.0"

[metadata]
task_id = "full_info"
task_type = "swe"
mode = "full_info"
repo_name = "navidrome/navidrome"
task_attempt_id = "69836ee4987091d7e86e448f__69c6a3d5874d3d3ac0297c55"
image_name = "hilbench-swe:69c6a3d5874d3d3ac0297c55"
tags = ["swe", "full_info", "hil-bench"]

[verifier]
timeout_sec = 1800.0

[agent]
timeout_sec = 7200.0

[environment]
docker_image = "hilbench-swe:69c6a3d5874d3d3ac0297c55"
build_timeout_sec = 1200.0
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
