schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_24-full_info"
description = ""
authors = []
keywords = []
[metadata]
task_id = "full_info"
task_type = "swe"
mode = "full_info"
repo_name = "ansible/ansible"
task_attempt_id = "69839e79db8f5e922c44f80c__69bf6d70aed83b2efbf355a1"
image_name = "hilbench-swe:69bf6d70aed83b2efbf355a1"
tags = [ "swe", "full_info", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "hilbench-swe:69bf6d70aed83b2efbf355a1"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
