schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_5-baseline"
description = ""
authors = []
keywords = []
[metadata]
task_id = "baseline"
task_type = "swe"
mode = "baseline"
repo_name = "ansible/ansible"
task_attempt_id = "69b37d1c972ca8745b4e8f69__69bcc6360c872b9773cce01d"
image_name = "hilbench-swe:69bcc6360c872b9773cce01d"
tags = [ "swe", "baseline", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "hilbench-swe:69bcc6360c872b9773cce01d"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
