version = "1.0"

[metadata]
task_id = "full_info"
task_type = "swe"
mode = "full_info"
repo_name = "ansible/ansible"
task_attempt_id = "69b37d1c972ca8745b4e8f69__69bcc6360c872b9773cce01d"
image_name = "hilbench-swe:69bcc6360c872b9773cce01d"
tags = ["swe", "full_info", "hil-bench"]

[verifier]
timeout_sec = 1800.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1200.0
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
