schema_version = "1.1"
artifacts = []
[task]
name = "scale-ai/hil-bench-swe_51-full_info"
description = ""
authors = []
keywords = []
[metadata]
task_id = "full_info"
task_type = "swe"
mode = "full_info"
repo_name = "navidrome/navidrome"
task_attempt_id = "698648c3283d42a760567547__69af9047352d3e1ddd448e1f"
image_name = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:cf34714005db8576690beb4dd901ac08f98bdb72e62914f921e1deaddbe13c27"
tags = [ "swe", "full_info", "hil-bench",]
[verifier]
timeout_sec = 1800.0

[verifier.env]
[agent]
timeout_sec = 7200.0
[environment]
build_timeout_sec = 1200.0
docker_image = "public.ecr.aws/b2z8n5q1/hil-bench@sha256:cf34714005db8576690beb4dd901ac08f98bdb72e62914f921e1deaddbe13c27"
os = "linux"
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
[solution.env]
